--
-- Create Schema Script 
--   Database Version   : 11.2.0.2.0 
--   Toad Version       : 10.1.1.8 
--   DB Connect String  : XE 
--   Schema             : DWH 
--   Script Created by  : SYS 
--   Script Created at  : 29/12/2022 21:16:32 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 21        Columns: 30         
--   Tables: 21         Columns: 121        Constraints: 60     


CREATE TABLE AGENT_DIM
(
  AGENT_KEY    NUMBER(8)                        NOT NULL,
  SNN          NUMBER(10)                       NOT NULL,
  NAME         VARCHAR2(30 BYTE)                NOT NULL,
  NATIONALITY  VARCHAR2(30 BYTE)                NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE AIRCRAFT_DIM
(
  AIRCRAFT_KEY     NUMBER(8)                    NOT NULL,
  AIRCRAFT_ID      VARCHAR2(50 BYTE)            NOT NULL,
  AIRCRAFT_NAME    VARCHAR2(50 BYTE)            NOT NULL,
  NO_OF_SEATS      NUMBER(3)                    NOT NULL,
  RUNNING_MILES    NUMBER(8),
  IN_SERVICE_FLAG  NUMBER(1)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE AIRPORT_DIM
(
  AIRPORT_KEY   NUMBER(4)                       NOT NULL,
  AIRPORT_CODE  VARCHAR2(40 BYTE)               NOT NULL,
  CITY          VARCHAR2(40 BYTE)               NOT NULL,
  COUNTRY       VARCHAR2(40 BYTE)               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLASS_OF_SERVICE_DIM
(
  CLASS_KEY    NUMBER(4,1)                      NOT NULL,
  CLASS_NAME   VARCHAR2(25 BYTE)                NOT NULL,
  CLASS_BONUS  NUMBER(3)                        NOT NULL,
  BASS_MILES   NUMBER(3)                        NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CUSTOMER_DIM
(
  CUSTOMER_KEY   NUMBER(8)                      NOT NULL,
  PASSPORT_ID    VARCHAR2(20 BYTE),
  NAME           VARCHAR2(20 BYTE)              NOT NULL,
  PHONE_NUMBER   VARCHAR2(20 BYTE)              NOT NULL,
  NATIONALITY    VARCHAR2(10 BYTE)              NOT NULL,
  FREQUENT_FLAG  NUMBER(1)                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CUSTOMER_INQUIRIES_FACT
(
  INQUIRY_KEY      NUMBER(15)                   NOT NULL,
  CUSTOMER_KEY     NUMBER(8)                    NOT NULL,
  AGENT_KEY        NUMBER(8)                    NOT NULL,
  CHANNEL_KEY      NUMBER(2)                    NOT NULL,
  INTERACTION_KEY  NUMBER(8)                    NOT NULL,
  FLIGHT_KEY       NUMBER(16)                   NOT NULL,
  DATE_KEY         NUMBER                       NOT NULL,
  STATUS           VARCHAR2(40 BYTE)            NOT NULL,
  FEEDBACK         NUMBER(1)                    NOT NULL,
  TIMING           VARCHAR2(20 BYTE)            NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DATEE_DIM
(
  DATE_KEY     NUMBER,
  FULL_DATE    DATE,
  DAYS         VARCHAR2(2 BYTE),
  MONTH_SHORT  VARCHAR2(12 BYTE),
  MONTH_NUM    VARCHAR2(2 BYTE),
  MONTH_LONG   VARCHAR2(36 BYTE),
  YEAR         VARCHAR2(4 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FAREBASE
(
  FARE_KEY          NUMBER(2)                   NOT NULL,
  BASE_FARE         NUMBER(4,2)                 NOT NULL,
  NO_OF_WAYS        NUMBER(1)                   NOT NULL,
  CHANGEABILITY     NUMBER                      NOT NULL,
  DIRECT_TICKETING  NUMBER                      NOT NULL,
  BAGGAE_FEES       NUMBER                      NOT NULL,
  TAX_AMOUNT        NUMBER                      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FLIGHT_DIM
(
  FLIGHT_KEY                NUMBER(16)          NOT NULL,
  DESTINATION_AIRPORT       NUMBER(4)           NOT NULL,
  ORIGIN_AIRPORT            NUMBER(4)           NOT NULL,
  SCHEDULED_ARRIVAL_DATE    NUMBER              NOT NULL,
  SCHEDULED_ARRIVAL_TIME    NUMBER              NOT NULL,
  SCHEDULED_DEPARTURE_DATE  NUMBER              NOT NULL,
  SCHEDULED_DEPARTURE_TIME  NUMBER              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FREQFLYER_CHANGABLE_DIM
(
  FREQFLYER_KEY     NUMBER(8)                   NOT NULL,
  PASSPORT_ID       VARCHAR2(30 BYTE)           NOT NULL,
  RANK_ID           NUMBER(2)                   NOT NULL,
  HOME_AIRPORT_KEY  NUMBER(4)                   NOT NULL,
  ACTUAL_MILES      VARCHAR2(40 BYTE),
  GAINED_MILES      VARCHAR2(40 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE FREQFLYER_SEGMENT_FACT
(
  PROFILE_KEY               NUMBER(8)           NOT NULL,
  FREQFLYER_KEY             NUMBER(8)           NOT NULL,
  FLIGHT_KEY                NUMBER(16)          NOT NULL,
  AIRCRAFT_KEY              NUMBER(8)           NOT NULL,
  ORIGIN_AIRPORT_KEY        NUMBER(4)           NOT NULL,
  DESTINATION_AIRPORT_KEY   NUMBER(4)           NOT NULL,
  CLASS_KEY                 NUMBER(4,1)         NOT NULL,
  PROMOTION_KEY             NUMBER(6)           NOT NULL,
  SALES_CHANNEL_KEY         NUMBER(2)           NOT NULL,
  SCHEDULED_ARRIVAL_DATE    NUMBER              NOT NULL,
  SCHEDULED_ARRIVAL_TIME    NUMBER              NOT NULL,
  SCHEDULED_DEPARTURE_DATE  NUMBER              NOT NULL,
  SCHEDULED_DEPARTURE_TIME  NUMBER              NOT NULL,
  ACTUAL_ARRIVAL_DATE       NUMBER              NOT NULL,
  ACTUAL_ARRIVAL_TIME       NUMBER              NOT NULL,
  ACTUAL_DEPARTURE_DATE     NUMBER              NOT NULL,
  ACTUAL_DEPARTURE_TIME     NUMBER              NOT NULL,
  SEGMENT_MILE_FLOWN        NUMBER(4)           NOT NULL,
  SEGMENT_MILE_EARNED       NUMBER(4)           NOT NULL,
  GROSS_SEGMENT_REVENUE     NUMBER(4)           NOT NULL,
  SEQ_SEG                   NUMBER(2),
  FAREBASE_FARE_KEY         NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE INTERACTION_DIM
(
  INTERACTION_KEY  NUMBER(8)                    NOT NULL,
  SEVERITY_KEY     NUMBER(2)                    NOT NULL,
  DESCRIPTION      VARCHAR2(100 BYTE)           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE INTER_CHANNEL_DIM
(
  CHANNEL_KEY   NUMBER(2)                       NOT NULL,
  CHANNEL_NAME  VARCHAR2(30 BYTE)               NOT NULL,
  DESCRIPTION   VARCHAR2(80 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LEG_FACT
(
  LEG_KEY         NUMBER(16)                    NOT NULL,
  FLIGHT_KEY      NUMBER(16)                    NOT NULL,
  ARRIVAL_DATE    NUMBER                        NOT NULL,
  ARRIVAL_TIME    NUMBER                        NOT NULL,
  DEPARTURE_DATE  NUMBER                        NOT NULL,
  DEPARTURE_TIME  NUMBER                        NOT NULL,
  LATE_TIME_MIN   NUMBER(2)                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROBLEM_DIM
(
  SEVERITY_KEY  NUMBER(2)                       NOT NULL,
  PROBLEM_NAME  VARCHAR2(50 BYTE)               NOT NULL,
  DEGREE        NUMBER(2)                       NOT NULL,
  DESCRIPTION   VARCHAR2(100 BYTE)              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROMOTION_DIM
(
  PROMOTION_KEY    NUMBER(6)                    NOT NULL,
  PROMOTION_TYPE   VARCHAR2(40 BYTE)            NOT NULL,
  EXPIRATION_DATE  NUMBER                       NOT NULL,
  STARTING_DATE    NUMBER                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROMOTION_FLYER_FACTLESS
(
  PROMOTION_FLYER_KEY  NUMBER(16)               NOT NULL,
  PROMOTION_KEY        NUMBER(6)                NOT NULL,
  FREQFLYER_KEY        NUMBER(8)                NOT NULL,
  DATA_KEY             NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PROPORTION_RANK_DIM
(
  RANK_KEY    NUMBER(2)                         NOT NULL,
  RANK_NAME   VARCHAR2(30 BYTE)                 NOT NULL,
  RANK_MILES  VARCHAR2(50 BYTE)                 NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SALES_CHANNEL_DIM
(
  SALES_CHANNEL_KEY   NUMBER(2)                 NOT NULL,
  SALES_CHANNEL_NAME  VARCHAR2(30 BYTE)         NOT NULL,
  PAYMENT_METHOD      VARCHAR2(30 BYTE)         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SALES_FACT
(
  TICKET_NUMBER      NUMBER(16)                 NOT NULL,
  FLIGHT_KEY         NUMBER(16)                 NOT NULL,
  PRICE              NUMBER(5)                  NOT NULL,
  DATE_KEY           NUMBER                     NOT NULL,
  SALES_CHANNEL_KEY  NUMBER(2)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIME_DIM
(
  TIME_KEY   NUMBER,
  FULL_TIME  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AGENT_DIM_PK ON AGENT_DIM
(AGENT_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX AIRCRAFT_DIM_PK ON AIRCRAFT_DIM
(AIRCRAFT_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX AIRPORT_DIM_PK ON AIRPORT_DIM
(AIRPORT_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CLASS_KEY ON CLASS_OF_SERVICE_DIM
(CLASS_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX CUSTOMER_INQUIRIES_FACT_PK ON CUSTOMER_INQUIRIES_FACT
(INQUIRY_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX DATEE_DIM_PK ON DATEE_DIM
(DATE_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FAREBASE_PK ON FAREBASE
(FARE_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FLIGHT_DIM_PK ON FLIGHT_DIM
(FLIGHT_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FREQFLYER_CHANGABLE_DIM_PK ON FREQFLYER_CHANGABLE_DIM
(FREQFLYER_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FREQFLYER_SEGMENT_FACT_PK ON FREQFLYER_SEGMENT_FACT
(PROFILE_KEY, FLIGHT_KEY, FREQFLYER_KEY, AIRCRAFT_KEY, ORIGIN_AIRPORT_KEY, 
DESTINATION_AIRPORT_KEY, CLASS_KEY, PROMOTION_KEY, SALES_CHANNEL_KEY, FAREBASE_FARE_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INTERACTION_DIM_PK ON INTERACTION_DIM
(INTERACTION_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX INTER_CHANNEL_DIM_PK ON INTER_CHANNEL_DIM
(CHANNEL_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX LEG_FACT_PK ON LEG_FACT
(LEG_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROBLEM_DIM_PK ON PROBLEM_DIM
(SEVERITY_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROMOTION_DIM_PK ON PROMOTION_DIM
(PROMOTION_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROMOTION_PER_FREQFLYER_FAC_PK ON PROMOTION_FLYER_FACTLESS
(PROMOTION_FLYER_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROPORTION_RANK_DIM_PK ON PROPORTION_RANK_DIM
(RANK_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SALES_CHANNEL_DIM_PK ON SALES_CHANNEL_DIM
(SALES_CHANNEL_KEY)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX SALES_FACT_PK ON SALES_FACT
(TICKET_NUMBER)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX TIME_DIM_PK ON TIME_DIM
(TIME_KEY)
LOGGING
NOPARALLEL;


ALTER TABLE AGENT_DIM ADD (
  CONSTRAINT AGENT_DIM_PK
 PRIMARY KEY
 (AGENT_KEY));

ALTER TABLE AIRCRAFT_DIM ADD (
  CONSTRAINT AIRCRAFT_DIM_PK
 PRIMARY KEY
 (AIRCRAFT_KEY));

ALTER TABLE AIRPORT_DIM ADD (
  CONSTRAINT AIRPORT_DIM_PK
 PRIMARY KEY
 (AIRPORT_KEY));

ALTER TABLE CLASS_OF_SERVICE_DIM ADD (
  CONSTRAINT CLASS_KEY
 PRIMARY KEY
 (CLASS_KEY));

ALTER TABLE CUSTOMER_DIM ADD (
  PRIMARY KEY
 (CUSTOMER_KEY));

ALTER TABLE CUSTOMER_INQUIRIES_FACT ADD (
  CONSTRAINT CUSTOMER_INQUIRIES_FACT_PK
 PRIMARY KEY
 (INQUIRY_KEY));

ALTER TABLE DATEE_DIM ADD (
  CONSTRAINT DATEE_DIM_PK
 PRIMARY KEY
 (DATE_KEY));

ALTER TABLE FAREBASE ADD (
  CONSTRAINT FAREBASE_PK
 PRIMARY KEY
 (FARE_KEY));

ALTER TABLE FLIGHT_DIM ADD (
  CONSTRAINT FLIGHT_DIM_PK
 PRIMARY KEY
 (FLIGHT_KEY));

ALTER TABLE FREQFLYER_CHANGABLE_DIM ADD (
  CONSTRAINT FREQFLYER_CHANGABLE_DIM_PK
 PRIMARY KEY
 (FREQFLYER_KEY));

ALTER TABLE FREQFLYER_SEGMENT_FACT ADD (
  CONSTRAINT FREQFLYER_SEGMENT_FACT_PK
 PRIMARY KEY
 (PROFILE_KEY, FLIGHT_KEY, FREQFLYER_KEY, AIRCRAFT_KEY, ORIGIN_AIRPORT_KEY, DESTINATION_AIRPORT_KEY, CLASS_KEY, PROMOTION_KEY, SALES_CHANNEL_KEY, FAREBASE_FARE_KEY));

ALTER TABLE INTERACTION_DIM ADD (
  CONSTRAINT INTERACTION_DIM_PK
 PRIMARY KEY
 (INTERACTION_KEY));

ALTER TABLE INTER_CHANNEL_DIM ADD (
  CONSTRAINT INTER_CHANNEL_DIM_PK
 PRIMARY KEY
 (CHANNEL_KEY));

ALTER TABLE LEG_FACT ADD (
  CONSTRAINT LEG_FACT_PK
 PRIMARY KEY
 (LEG_KEY));

ALTER TABLE PROBLEM_DIM ADD (
  CONSTRAINT PROBLEM_DIM_PK
 PRIMARY KEY
 (SEVERITY_KEY));

ALTER TABLE PROMOTION_DIM ADD (
  CONSTRAINT PROMOTION_DIM_PK
 PRIMARY KEY
 (PROMOTION_KEY));

ALTER TABLE PROMOTION_FLYER_FACTLESS ADD (
  CONSTRAINT PROMOTION_PER_FREQFLYER_FAC_PK
 PRIMARY KEY
 (PROMOTION_FLYER_KEY));

ALTER TABLE PROPORTION_RANK_DIM ADD (
  CONSTRAINT PROPORTION_RANK_DIM_PK
 PRIMARY KEY
 (RANK_KEY));

ALTER TABLE SALES_CHANNEL_DIM ADD (
  CONSTRAINT SALES_CHANNEL_DIM_PK
 PRIMARY KEY
 (SALES_CHANNEL_KEY));

ALTER TABLE SALES_FACT ADD (
  CONSTRAINT SALES_FACT_PK
 PRIMARY KEY
 (TICKET_NUMBER));

ALTER TABLE TIME_DIM ADD (
  CONSTRAINT TIME_DIM_PK
 PRIMARY KEY
 (TIME_KEY));

ALTER TABLE FLIGHT_DIM ADD (
  CONSTRAINT FLIGHT_DIM_AIRPORT_DIM 
 FOREIGN KEY (DESTINATION_AIRPORT) 
 REFERENCES AIRPORT_DIM (AIRPORT_KEY),
  CONSTRAINT FLIGHT_DIM_AIRPORT_DIM_1 
 FOREIGN KEY (ORIGIN_AIRPORT) 
 REFERENCES AIRPORT_DIM (AIRPORT_KEY),
  CONSTRAINT FLIGHT_DIM_R03 
 FOREIGN KEY (SCHEDULED_ARRIVAL_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT FLIGHT_DIM_R04 
 FOREIGN KEY (SCHEDULED_DEPARTURE_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT FLIGHT_DIM_R05 
 FOREIGN KEY (SCHEDULED_ARRIVAL_TIME) 
 REFERENCES TIME_DIM (TIME_KEY),
  CONSTRAINT FLIGHT_DIM_R06 
 FOREIGN KEY (SCHEDULED_DEPARTURE_TIME) 
 REFERENCES TIME_DIM (TIME_KEY));

ALTER TABLE FREQFLYER_CHANGABLE_DIM ADD (
  CONSTRAINT FREQFLYER_AIRPORT_DIM 
 FOREIGN KEY (HOME_AIRPORT_KEY) 
 REFERENCES AIRPORT_DIM (AIRPORT_KEY),
  CONSTRAINT FREQFLYER_DIM_RANK_1 
 FOREIGN KEY (RANK_ID) 
 REFERENCES PROPORTION_RANK_DIM (RANK_KEY));

ALTER TABLE FREQFLYER_SEGMENT_FACT ADD (
  CONSTRAINT FREQFLYERSS_OF_SERVICE_DIM 
 FOREIGN KEY (CLASS_KEY) 
 REFERENCES CLASS_OF_SERVICE_DIM (CLASS_KEY),
  CONSTRAINT FREQFLYER_AIRCRAFT_DIM 
 FOREIGN KEY (AIRCRAFT_KEY) 
 REFERENCES AIRCRAFT_DIM (AIRCRAFT_KEY),
  CONSTRAINT FREQFLYER_CHANGABLE_DIM 
 FOREIGN KEY (FREQFLYER_KEY) 
 REFERENCES FREQFLYER_CHANGABLE_DIM (FREQFLYER_KEY),
  CONSTRAINT FREQFLYER_DIM 
 FOREIGN KEY (DESTINATION_AIRPORT_KEY) 
 REFERENCES AIRPORT_DIM (AIRPORT_KEY),
  CONSTRAINT FREQFLYER_DIM_1 
 FOREIGN KEY (FLIGHT_KEY) 
 REFERENCES FLIGHT_DIM (FLIGHT_KEY),
  CONSTRAINT FREQFLYER_FACT_AIRPORT_DIM 
 FOREIGN KEY (ORIGIN_AIRPORT_KEY) 
 REFERENCES AIRPORT_DIM (AIRPORT_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R09 
 FOREIGN KEY (PROMOTION_KEY) 
 REFERENCES PROMOTION_DIM (PROMOTION_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R10 
 FOREIGN KEY (SCHEDULED_ARRIVAL_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R11 
 FOREIGN KEY (SCHEDULED_DEPARTURE_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R12 
 FOREIGN KEY (ACTUAL_ARRIVAL_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R13 
 FOREIGN KEY (ACTUAL_DEPARTURE_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R14 
 FOREIGN KEY (ACTUAL_ARRIVAL_TIME) 
 REFERENCES TIME_DIM (TIME_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R16 
 FOREIGN KEY (ACTUAL_DEPARTURE_TIME) 
 REFERENCES TIME_DIM (TIME_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R17 
 FOREIGN KEY (SCHEDULED_ARRIVAL_TIME) 
 REFERENCES TIME_DIM (TIME_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R18 
 FOREIGN KEY (SCHEDULED_DEPARTURE_TIME) 
 REFERENCES TIME_DIM (TIME_KEY),
  CONSTRAINT FREQFLYER_SEGMENT_FACT_R50 
 FOREIGN KEY (PROFILE_KEY) 
 REFERENCES CUSTOMER_DIM (CUSTOMER_KEY),
  CONSTRAINT FREQFLYE_CHANNEL_DIM 
 FOREIGN KEY (SALES_CHANNEL_KEY) 
 REFERENCES SALES_CHANNEL_DIM (SALES_CHANNEL_KEY));

ALTER TABLE INTERACTION_DIM ADD (
  CONSTRAINT INTERACTION_DIM_PROBLEM 
 FOREIGN KEY (SEVERITY_KEY) 
 REFERENCES PROBLEM_DIM (SEVERITY_KEY));

ALTER TABLE LEG_FACT ADD (
  CONSTRAINT LEG_FACT_FLIGHT_DIM 
 FOREIGN KEY (FLIGHT_KEY) 
 REFERENCES FLIGHT_DIM (FLIGHT_KEY),
  CONSTRAINT LEG_FACT_R02 
 FOREIGN KEY (ARRIVAL_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT LEG_FACT_R03 
 FOREIGN KEY (DEPARTURE_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT LEG_FACT_R04 
 FOREIGN KEY (ARRIVAL_TIME) 
 REFERENCES TIME_DIM (TIME_KEY),
  CONSTRAINT LEG_FACT_R05 
 FOREIGN KEY (DEPARTURE_TIME) 
 REFERENCES TIME_DIM (TIME_KEY));

ALTER TABLE PROMOTION_DIM ADD (
  CONSTRAINT PROMOTION_DIM_R01 
 FOREIGN KEY (EXPIRATION_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT PROMOTION_DIM_R02 
 FOREIGN KEY (STARTING_DATE) 
 REFERENCES DATEE_DIM (DATE_KEY));

ALTER TABLE PROMOTION_FLYER_FACTLESS ADD (
  CONSTRAINT PROMOTION_FLYER_FACTLESS_R03 
 FOREIGN KEY (DATA_KEY) 
 REFERENCES DATEE_DIM (DATE_KEY),
  CONSTRAINT PROMOTION_PROMOTION_DIM 
 FOREIGN KEY (PROMOTION_KEY) 
 REFERENCES PROMOTION_DIM (PROMOTION_KEY),
  CONSTRAINT PYER_CHANGABLE_DIM 
 FOREIGN KEY (FREQFLYER_KEY) 
 REFERENCES FREQFLYER_CHANGABLE_DIM (FREQFLYER_KEY));

ALTER TABLE SALES_FACT ADD (
  CONSTRAINT SALES_FACT_R01 
 FOREIGN KEY (FLIGHT_KEY) 
 REFERENCES FLIGHT_DIM (FLIGHT_KEY),
  CONSTRAINT SALES_FACT_R02 
 FOREIGN KEY (SALES_CHANNEL_KEY) 
 REFERENCES SALES_CHANNEL_DIM (SALES_CHANNEL_KEY),
  CONSTRAINT SALES_FACT_R03 
 FOREIGN KEY (DATE_KEY) 
 REFERENCES DATEE_DIM (DATE_KEY));